#
# Config file for oh-my-posh prompt 
# https://ohmyposh.dev/
#

version = 2
final_space = true
console_title_template = '{{ if .Root }}ROOT{{else}}{{ .UserName }}{{end}} in {{ .PWD }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '{{ if .Root }}ROOT{{else}}{{ .UserName }}{{end}}@{{ .HostName }}'
    foreground = 'yellow'
    background = 'transparent'
    foreground_templates = [
        "{{if .Root}}red{{end}}",
    ]

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#6c6c6c'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <red>{{ if gt .Behind 0 }}↓{{ end }}{{ if gt .Ahead 0 }}↑{{ end }}</>'

    [blocks.segments.properties]
      fetch_status = true
      commit_icon = '@'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'
 
  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'red'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000
      style = 'austin'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .PWD }}'
    background = 'transparent'
    foreground = 'blue'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ' >'
    foreground = 'blue'
    background = 'transparent'

[secondary_prompt]
  foreground = 'blue'
  background = 'transparent'
  template = '>> '



